Updating argocd action
sumup/payments-reusable-workflows pull request #46
Opened 2022-09-02 19:59 UTC by mtsvyatkovski

2022-09-14 10:23 UTC, ivandivasilev approved these changes

2022-09-15 10:24 UTC, syndbg requested changes

2022-09-15 10:24 UTC, syndbg commented on .github/workflows/build-deploy-dev.yaml
> +      slack_short_format:
Imo, `slack_message_format` is more descriptive.

This also suggests changing the value type from bool to string.
The benefit of this would be that we can provide more options in the future. 
E.g `short`, `full`, `something-new` eventually.

2022-09-15 10:24 UTC, syndbg commented on .github/workflows/build-release.yaml
> +      slack_short_format:
ditto `slack_short_format`

2022-09-15 10:24 UTC, syndbg commented on .github/workflows/build-release.yaml
> +      auto_merge:
I suggest these this to be `stage_auto_merge`.

2022-09-15 10:24 UTC, syndbg commented on .github/workflows/build-release.yaml
> +      argocd_auto_sync:
Imo, `stage_argocd_auto_sync`

2022-09-15 10:24 UTC, syndbg commented on .github/workflows/build-release.yaml
> +      - name: "Testing github event"
✂️

2022-09-21 10:58 UTC, syndbg approved these changes

2022-09-21 11:08 UTC, merged