Moving refactored workflows
sumup/payments-reusable-workflows pull request #59
Opened 2022-10-12 12:42 UTC by mtsvyatkovski

2022-10-12 13:14 UTC, ivandivasilev approved these changes

2022-10-13 10:39 UTC, syndbg commented on .github/workflows/__argocd_sync.yaml
> +          ref: '0.10.2'
We can wrap these under a reusable workflow, so that we reference it more easily.

2022-10-13 11:02 UTC, syndbg requested changes

2022-10-14 07:54 UTC, ivandivasilev commented on .github/workflows/__argocd_sync.yaml
> +          ref: '0.10.2'
I do not think so, because each job runs in a separate runner.

2022-10-19 12:17 UTC, merged